### PR TITLE
fixed inconsistent root node

### PR DESCRIPTION
**Pull request by JanEggers**
fix for #146

### CODE REVIEW

**Comment by rychkog** [comment]
@JanEggers Thanks for the fix! Could you, please, fix the conflicts and [failing build](https://travis-ci.org/valor-software/ng2-tree/builds/292459976?utm_source=github_status&utm_medium=notification)? Once done - will merge it straight away

**Comment by JanEggers** [comment]
rebase is done

**Comment by JanEggers** [comment]
@rychkog ping

**Comment by rychkog** [comment]
@JanEggers Merged

**Comment by JanEggers** [comment]
thx

**Pull request merged**
